/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class ContactImpulse {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ContactImpulse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContactImpulse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ContactImpulse obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_ContactImpulse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNormalImpulses(SWIGTYPE_p_float value) {
    liquidfunJNI.ContactImpulse_normalImpulses_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getNormalImpulses() {
    long cPtr = liquidfunJNI.ContactImpulse_normalImpulses_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setTangentImpulses(SWIGTYPE_p_float value) {
    liquidfunJNI.ContactImpulse_tangentImpulses_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getTangentImpulses() {
    long cPtr = liquidfunJNI.ContactImpulse_tangentImpulses_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setCount(int value) {
    liquidfunJNI.ContactImpulse_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return liquidfunJNI.ContactImpulse_count_get(swigCPtr, this);
  }

  public float getFirstNormalImpulse() {
    return liquidfunJNI.ContactImpulse_getFirstNormalImpulse(swigCPtr, this);
  }

  public ContactImpulse() {
    this(liquidfunJNI.new_ContactImpulse(), true);
  }

}
